package cz.vsmie.krist.pms.logging.dto;

/**
 *
 * @author Jan Krist
 */

// Generated 13.5.2013 22:06:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoggingEventProperty generated by hbm2java
 */
@Entity
@Table(name = "logging_event_property")
public class LoggingEventProperty implements java.io.Serializable {

	@Id @GeneratedValue
        @Column(name = "event_id", unique = true, nullable = false)
        private Long id;
        
        @ManyToOne(fetch = FetchType.LAZY)
        @JoinColumn(name = "event_id", nullable = false, insertable = false, updatable = false)
	private LoggingEvent loggingEvent;
        @Column(name = "mapped_value", length = 65535)
	private String mappedValue;
        @Column(name = "mapped_key", length = 254)
	private String mappedKey;
        
        
        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

	

        public LoggingEvent getLoggingEvent() {
            return this.loggingEvent;
	}

	public void setLoggingEvent(LoggingEvent loggingEvent) {
            this.loggingEvent = loggingEvent;
	}

        public String getMappedValue() {
		return this.mappedValue;
	}

	public void setMappedValue(String mappedValue) {
		this.mappedValue = mappedValue;
	}

    public String getMappedKey() {
        return mappedKey;
    }

    public void setMappedKey(String mappedKey) {
        this.mappedKey = mappedKey;
    }

    

}
