package cz.vsmie.krist.pms.logging.dto;

// Generated 13.5.2013 22:06:11 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoggingEvent generated by hbm2java
 */
@Entity
@Table(name = "logging_event", catalog = "pms")
public class LoggingEvent implements java.io.Serializable {
    
    @Id
    @GeneratedValue
    @Column(name = "event_id", unique = true, nullable = false)
    private Long eventId;
    @Column(name = "timestmp", nullable = false)
    private long timestmp;
    @Column(name = "formatted_message", nullable = false, length = 65535)
    private String formattedMessage;
    @Column(name = "logger_name", nullable = false, length = 254)
    private String loggerName;
    @Column(name = "level_string", nullable = false, length = 254)
    private String levelString;
    @Column(name = "thread_name", length = 254)
    private String threadName;
    @Column(name = "reference_flag")
    private Short referenceFlag;
    @Column(name = "arg0", length = 254)
    private String arg0;
    @Column(name = "arg1", length = 254)
    private String arg1;
    @Column(name = "arg2", length = 254)
    private String arg2;
    @Column(name = "arg3", length = 254)
    private String arg3;
    @Column(name = "caller_filename", nullable = false, length = 254)
    private String callerFilename;
    @Column(name = "caller_class", nullable = false, length = 254)
    private String callerClass;
    @Column(name = "caller_method", nullable = false, length = 254)
    private String callerMethod;
    @Column(name = "caller_line", nullable = false, length = 4)
    private String callerLine;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loggingEvent")
    private Set<LoggingEventException> loggingEventExceptions = new HashSet(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loggingEvent")
    private Set<LoggingEventProperty> loggingEventProperties = new HashSet(0);

    public LoggingEvent() {
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public long getTimestmp() {
        return this.timestmp;
    }

    public void setTimestmp(long timestmp) {
        this.timestmp = timestmp;
    }

    public String getFormattedMessage() {
        return this.formattedMessage;
    }

    public void setFormattedMessage(String formattedMessage) {
        this.formattedMessage = formattedMessage;
    }

    public String getLoggerName() {
        return this.loggerName;
    }

    public void setLoggerName(String loggerName) {
        this.loggerName = loggerName;
    }

    public String getLevelString() {
        return this.levelString;
    }

    public void setLevelString(String levelString) {
        this.levelString = levelString;
    }

    public String getThreadName() {
        return this.threadName;
    }

    public void setThreadName(String threadName) {
        this.threadName = threadName;
    }

    public Short getReferenceFlag() {
        return this.referenceFlag;
    }

    public void setReferenceFlag(Short referenceFlag) {
        this.referenceFlag = referenceFlag;
    }

    public String getArg0() {
        return this.arg0;
    }

    public void setArg0(String arg0) {
        this.arg0 = arg0;
    }

    public String getArg1() {
        return this.arg1;
    }

    public void setArg1(String arg1) {
        this.arg1 = arg1;
    }

    public String getArg2() {
        return this.arg2;
    }

    public void setArg2(String arg2) {
        this.arg2 = arg2;
    }

    public String getArg3() {
        return this.arg3;
    }

    public void setArg3(String arg3) {
        this.arg3 = arg3;
    }

    public String getCallerFilename() {
        return this.callerFilename;
    }

    public void setCallerFilename(String callerFilename) {
        this.callerFilename = callerFilename;
    }

    public String getCallerClass() {
        return this.callerClass;
    }

    public void setCallerClass(String callerClass) {
        this.callerClass = callerClass;
    }

    public String getCallerMethod() {
        return this.callerMethod;
    }

    public void setCallerMethod(String callerMethod) {
        this.callerMethod = callerMethod;
    }

    public String getCallerLine() {
        return this.callerLine;
    }

    public void setCallerLine(String callerLine) {
            this.callerLine = callerLine;
    }

    public Set<LoggingEventException> getLoggingEventExceptions() {
        return loggingEventExceptions;
    }

    public void setLoggingEventExceptions(Set<LoggingEventException> loggingEventExceptions) {
        this.loggingEventExceptions = loggingEventExceptions;
    }

    public Set<LoggingEventProperty> getLoggingEventProperties() {
        return loggingEventProperties;
    }

    public void setLoggingEventProperties(Set<LoggingEventProperty> loggingEventProperties) {
        this.loggingEventProperties = loggingEventProperties;
    }

    

}
